package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"
	"fmt"

	"github.com/epitech/timemanager/internal/graph"
	"github.com/epitech/timemanager/internal/graph/model"
)

// User mutation resolvers implemented in userResolvers.go

// CreateTimeEntry is the resolver for the createTimeEntry field.
func (r *mutationResolver) CreateTimeEntry(ctx context.Context, input model.CreateTimeEntryInput) (*model.TimeTableEntry, error) {
	panic(fmt.Errorf("not implemented: CreateTimeEntry - createTimeEntry"))
}

// UpdateTimeEntry is the resolver for the updateTimeEntry field.
func (r *mutationResolver) UpdateTimeEntry(ctx context.Context, id string, input model.UpdateTimeEntryInput) (*model.TimeTableEntry, error) {
	panic(fmt.Errorf("not implemented: UpdateTimeEntry - updateTimeEntry"))
}

// DeleteTimeEntry is the resolver for the deleteTimeEntry field.
func (r *mutationResolver) DeleteTimeEntry(ctx context.Context, id string) (bool, error) {
	panic(fmt.Errorf("not implemented: DeleteTimeEntry - deleteTimeEntry"))
}

// Roles is the resolver for the roles field.
func (r *queryResolver) Roles(ctx context.Context) ([]model.Role, error) {
	panic(fmt.Errorf("not implemented: Roles - roles"))
}

// TimeTables is the resolver for the timeTables field.
func (r *queryResolver) TimeTables(ctx context.Context) ([]*model.TimeTable, error) {
	panic(fmt.Errorf("not implemented: TimeTables - timeTables"))
}

// Mutation returns graph.MutationResolver implementation.
func (r *Resolver) Mutation() graph.MutationResolver { return &mutationResolver{r} }

// Query returns graph.QueryResolver implementation.
func (r *Resolver) Query() graph.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
