// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"
)

type AddUsersToTeamInput struct {
	UserIDs []string `json:"userIDs"`
	TeamID  string   `json:"teamID"`
}

type CreateMassiveUsersInput struct {
	Users []*CreateUserInput `json:"users"`
}

type CreateTeamInput struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	ManagerID   string `json:"managerID"`
}

type CreateTimeEntryInput struct {
	UserID    string     `json:"userID"`
	Day       string     `json:"day"`
	Arrival   time.Time  `json:"arrival"`
	Departure *time.Time `json:"departure,omitempty"`
	Status    bool       `json:"status"`
}

type CreateUserInput struct {
	FirstName string `json:"firstName"`
	LastName  string `json:"lastName"`
	Email     string `json:"email"`
	Phone     string `json:"phone"`
	Password  string `json:"password"`
	Role      Role   `json:"role"`
}

type Mutation struct {
}

type Query struct {
}

type SignUpInput struct {
	FirstName string `json:"firstName"`
	LastName  string `json:"lastName"`
	Email     string `json:"email"`
	Phone     string `json:"phone"`
	Password  string `json:"password"`
}

type Team struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	ManagerID   *User  `json:"managerID"`
}

type TeamUser struct {
	ID     string `json:"id"`
	UserID *User  `json:"userID"`
	TeamID *Team  `json:"teamID"`
}

type TimeTable struct {
	ID     string    `json:"id"`
	UserID *User     `json:"userID"`
	Day    string    `json:"day"`
	Start  time.Time `json:"start"`
	End    time.Time `json:"end"`
}

type TimeTableEntry struct {
	ID        string     `json:"id"`
	UserID    *User      `json:"userID"`
	Day       string     `json:"day"`
	Arrival   time.Time  `json:"arrival"`
	Departure *time.Time `json:"departure,omitempty"`
	Status    bool       `json:"status"`
}

type UpdateProfileInput struct {
	FirstName *string `json:"firstName,omitempty"`
	LastName  *string `json:"lastName,omitempty"`
	Email     *string `json:"email,omitempty"`
	Phone     *string `json:"phone,omitempty"`
	Password  *string `json:"password,omitempty"`
}

type UpdateTeamInput struct {
	Name        *string `json:"name,omitempty"`
	Description *string `json:"description,omitempty"`
	ManagerID   *string `json:"managerID,omitempty"`
}

type UpdateTimeEntryInput struct {
	UserID    *string    `json:"userID,omitempty"`
	Day       *string    `json:"day,omitempty"`
	Arrival   *time.Time `json:"arrival,omitempty"`
	Departure *time.Time `json:"departure,omitempty"`
	Status    *bool      `json:"status,omitempty"`
}

type UpdateUserInput struct {
	FirstName *string `json:"firstName,omitempty"`
	LastName  *string `json:"lastName,omitempty"`
	Email     *string `json:"email,omitempty"`
	Phone     *string `json:"phone,omitempty"`
	Password  *string `json:"password,omitempty"`
	Role      *Role   `json:"role,omitempty"`
}

type User struct {
	ID        string `json:"id"`
	FirstName string `json:"firstName"`
	LastName  string `json:"lastName"`
	Email     string `json:"email"`
	Phone     string `json:"phone"`
	Password  string `json:"password"`
	Role      Role   `json:"role"`
}

type UserLogged struct {
	FirstName string `json:"firstName"`
	LastName  string `json:"lastName"`
	Email     string `json:"email"`
	Phone     string `json:"phone"`
	Role      Role   `json:"role"`
	Token     string `json:"token"`
}

type UserWithAllData struct {
	ID               string            `json:"id"`
	FirstName        string            `json:"firstName"`
	LastName         string            `json:"lastName"`
	Email            string            `json:"email"`
	Phone            string            `json:"phone"`
	Password         string            `json:"password"`
	Role             Role              `json:"role"`
	Teams            []*Team           `json:"teams"`
	TimeTableEntries []*TimeTableEntry `json:"timeTableEntries"`
	TimeTables       []*TimeTable      `json:"timeTables"`
}

type Role string

const (
	RoleUser    Role = "USER"
	RoleAdmin   Role = "ADMIN"
	RoleManager Role = "MANAGER"
)

var AllRole = []Role{
	RoleUser,
	RoleAdmin,
	RoleManager,
}

func (e Role) IsValid() bool {
	switch e {
	case RoleUser, RoleAdmin, RoleManager:
		return true
	}
	return false
}

func (e Role) String() string {
	return string(e)
}

func (e *Role) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Role(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Role", str)
	}
	return nil
}

func (e Role) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *Role) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e Role) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
