// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"
)

type AddUsersToTeamInput struct {
	UserIDs []string `json:"userIDs"`
	TeamID  string   `json:"teamID"`
}

type AdminKpiDashboard struct {
	Period       *DateRange            `json:"period"`
	Summary      *AdminKpiSummary      `json:"summary"`
	Workload     *WorkloadAnalysis     `json:"workload"`
	Punctuality  *PunctualityMetrics   `json:"punctuality"`
	Overtime     *OvertimeReport       `json:"overtime"`
	Compliance   *ComplianceMetrics    `json:"compliance"`
	Productivity *ProductivityMetrics  `json:"productivity"`
	Teams        []*TeamDetailedReport `json:"teams"`
}

type AdminKpiSummary struct {
	TotalUsers       int32   `json:"totalUsers"`
	ActiveUsers      int32   `json:"activeUsers"`
	TotalTeams       int32   `json:"totalTeams"`
	TotalWorkedHours int32   `json:"totalWorkedHours"`
	AvgHoursPerUser  float64 `json:"avgHoursPerUser"`
	ComplianceRate   float64 `json:"complianceRate"`
}

type ComplianceAnomaly struct {
	Type          string `json:"type"`
	Count         int32  `json:"count"`
	Severity      string `json:"severity"`
	AffectedUsers int32  `json:"affectedUsers"`
}

type ComplianceMetrics struct {
	MissingEntriesCount    int32                `json:"missingEntriesCount"`
	IncompleteEntriesCount int32                `json:"incompleteEntriesCount"`
	AnomaliesCount         int32                `json:"anomaliesCount"`
	ComplianceRate         float64              `json:"complianceRate"`
	UsersWithIssues        int32                `json:"usersWithIssues"`
	Anomalies              []*ComplianceAnomaly `json:"anomalies"`
}

type CoveragePoint struct {
	Time  time.Time `json:"time"`
	Count int32     `json:"count"`
}

type CreateMassiveUsersInput struct {
	Users []*CreateUserInput `json:"users"`
}

type CreateTeamInput struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	ManagerID   string `json:"managerID"`
}

type CreateTimeEntryInput struct {
	UserID    string     `json:"userID"`
	Day       string     `json:"day"`
	Arrival   time.Time  `json:"arrival"`
	Departure *time.Time `json:"departure,omitempty"`
	Status    bool       `json:"status"`
}

type CreateUserInput struct {
	FirstName string `json:"firstName"`
	LastName  string `json:"lastName"`
	Email     string `json:"email"`
	Phone     string `json:"phone"`
	Password  string `json:"password"`
	Role      Role   `json:"role"`
}

type DateRange struct {
	From string `json:"from"`
	To   string `json:"to"`
}

type DayDistribution struct {
	Day          string  `json:"day"`
	AvgMinutes   float64 `json:"avgMinutes"`
	TotalMinutes int32   `json:"totalMinutes"`
}

type KpiPoint struct {
	Date    string `json:"date"`
	Minutes int32  `json:"minutes"`
}

type Mutation struct {
}

type OvertimeByPeriod struct {
	PeriodStart  string `json:"periodStart"`
	TotalMinutes int32  `json:"totalMinutes"`
	UsersCount   int32  `json:"usersCount"`
}

type OvertimeReport struct {
	TotalOvertimeMinutes int32                 `json:"totalOvertimeMinutes"`
	AvgOvertimePerUser   float64               `json:"avgOvertimePerUser"`
	UsersWithOvertime    int32                 `json:"usersWithOvertime"`
	TopOvertimeUsers     []*UserOvertimeDetail `json:"topOvertimeUsers"`
	OvertimeByWeek       []*OvertimeByPeriod   `json:"overtimeByWeek"`
}

type ProductivityMetrics struct {
	AvgEfficiencyRate    float64                   `json:"avgEfficiencyRate"`
	TotalProductiveHours int32                     `json:"totalProductiveHours"`
	AvgHoursPerUser      float64                   `json:"avgHoursPerUser"`
	TopPerformers        []*UserProductivityDetail `json:"topPerformers"`
	ProductivityTrend    []*ProductivityTrend      `json:"productivityTrend"`
}

type ProductivityTrend struct {
	Date          string  `json:"date"`
	AvgEfficiency float64 `json:"avgEfficiency"`
	TotalHours    int32   `json:"totalHours"`
}

type PunctualityMetrics struct {
	OnTimeRate         float64             `json:"onTimeRate"`
	LateRate           float64             `json:"lateRate"`
	AvgLateMinutes     float64             `json:"avgLateMinutes"`
	TotalLateIncidents int32               `json:"totalLateIncidents"`
	PunctualUsers      int32               `json:"punctualUsers"`
	LateUsers          int32               `json:"lateUsers"`
	TrendByWeek        []*PunctualityTrend `json:"trendByWeek"`
}

type PunctualityTrend struct {
	WeekStart      string  `json:"weekStart"`
	OnTimeRate     float64 `json:"onTimeRate"`
	AvgLateMinutes float64 `json:"avgLateMinutes"`
}

type Query struct {
}

type SignUpInput struct {
	FirstName string `json:"firstName"`
	LastName  string `json:"lastName"`
	Email     string `json:"email"`
	Phone     string `json:"phone"`
	Password  string `json:"password"`
}

type SignedUser struct {
	ID            string  `json:"id"`
	FirstName     string  `json:"firstName"`
	LastName      string  `json:"lastName"`
	Email         string  `json:"email"`
	Password      string  `json:"password"`
	Role          Role    `json:"role"`
	Phone         string  `json:"phone"`
	HasStartedDay bool    `json:"hasStartedDay"`
	StartedAt     *string `json:"startedAt,omitempty"`
}

type Team struct {
	ID          string             `json:"id"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	ManagerID   *User              `json:"managerID"`
	Users       []*UserWithAllData `json:"users"`
}

type TeamDetailedReport struct {
	TeamID               string                    `json:"teamID"`
	TeamName             string                    `json:"teamName"`
	MemberCount          int32                     `json:"memberCount"`
	TotalWorkedMinutes   int32                     `json:"totalWorkedMinutes"`
	AvgMinutesPerMember  float64                   `json:"avgMinutesPerMember"`
	ActiveNow            int32                     `json:"activeNow"`
	TopContributors      []*TeamMemberContribution `json:"topContributors"`
	WorkloadDistribution []*WorkloadDistribution   `json:"workloadDistribution"`
}

type TeamKpiSummary struct {
	From                    string           `json:"from"`
	To                      string           `json:"to"`
	TeamID                  string           `json:"teamID"`
	TotalWorkedMinutes      int32            `json:"totalWorkedMinutes"`
	AvgWorkedMinutesPerUser float64          `json:"avgWorkedMinutesPerUser"`
	ActiveUsers             int32            `json:"activeUsers"`
	Coverage                []*CoveragePoint `json:"coverage"`
}

type TeamMemberContribution struct {
	UserID          string `json:"userID"`
	UserName        string `json:"userName"`
	WorkedMinutes   int32  `json:"workedMinutes"`
	DaysPresent     int32  `json:"daysPresent"`
	OvertimeMinutes int32  `json:"overtimeMinutes"`
}

type TeamUser struct {
	UserID *User `json:"userID"`
	TeamID *Team `json:"teamID"`
}

type TimeTable struct {
	ID            string     `json:"id"`
	Start         time.Time  `json:"start"`
	Ends          time.Time  `json:"ends"`
	EffectiveFrom time.Time  `json:"effectiveFrom"`
	EffectiveTo   *time.Time `json:"effectiveTo,omitempty"`
	IsActive      bool       `json:"isActive"`
}

type TimeTableEntry struct {
	ID        string     `json:"id"`
	UserID    *User      `json:"userID"`
	Day       string     `json:"day"`
	Arrival   time.Time  `json:"arrival"`
	Departure *time.Time `json:"departure,omitempty"`
	Status    bool       `json:"status"`
}

type UpdateProfileInput struct {
	FirstName *string `json:"firstName,omitempty"`
	LastName  *string `json:"lastName,omitempty"`
	Email     *string `json:"email,omitempty"`
	Phone     *string `json:"phone,omitempty"`
	Password  *string `json:"password,omitempty"`
}

type UpdateTeamInput struct {
	Name        *string `json:"name,omitempty"`
	Description *string `json:"description,omitempty"`
	ManagerID   *string `json:"managerID,omitempty"`
}

type UpdateTimeEntryInput struct {
	UserID    *string    `json:"userID,omitempty"`
	Day       *string    `json:"day,omitempty"`
	Arrival   *time.Time `json:"arrival,omitempty"`
	Departure *time.Time `json:"departure,omitempty"`
	Status    *bool      `json:"status,omitempty"`
}

type UpdateUserInput struct {
	FirstName *string `json:"firstName,omitempty"`
	LastName  *string `json:"lastName,omitempty"`
	Email     *string `json:"email,omitempty"`
	Phone     *string `json:"phone,omitempty"`
	Password  *string `json:"password,omitempty"`
	Role      *Role   `json:"role,omitempty"`
}

type User struct {
	ID        string `json:"id"`
	FirstName string `json:"firstName"`
	LastName  string `json:"lastName"`
	Email     string `json:"email"`
	Phone     string `json:"phone"`
	Password  string `json:"password"`
	Role      Role   `json:"role"`
}

type UserKpiSummary struct {
	From              string      `json:"from"`
	To                string      `json:"to"`
	UserID            string      `json:"userID"`
	WorkedMinutes     int32       `json:"workedMinutes"`
	OvertimeMinutes   int32       `json:"overtimeMinutes"`
	DaysPresent       int32       `json:"daysPresent"`
	CurrentStreakDays int32       `json:"currentStreakDays"`
	PunctualityRate   float64     `json:"punctualityRate"`
	PresentNow        bool        `json:"presentNow"`
	DailyWorked       []*KpiPoint `json:"dailyWorked"`
}

type UserLogged struct {
	FirstName string `json:"firstName"`
	LastName  string `json:"lastName"`
	Email     string `json:"email"`
	Phone     string `json:"phone"`
	Role      Role   `json:"role"`
	Token     string `json:"token"`
}

type UserOvertimeDetail struct {
	UserID          string `json:"userID"`
	UserName        string `json:"userName"`
	OvertimeMinutes int32  `json:"overtimeMinutes"`
	DaysWorked      int32  `json:"daysWorked"`
}

type UserProductivityDetail struct {
	UserID         string  `json:"userID"`
	UserName       string  `json:"userName"`
	EfficiencyRate float64 `json:"efficiencyRate"`
	TotalHours     int32   `json:"totalHours"`
}

type UserWithAllData struct {
	ID               string            `json:"id"`
	FirstName        string            `json:"firstName"`
	LastName         string            `json:"lastName"`
	Email            string            `json:"email"`
	Phone            string            `json:"phone"`
	Password         string            `json:"password"`
	Role             Role              `json:"role"`
	Teams            []*Team           `json:"teams"`
	TimeTableEntries []*TimeTableEntry `json:"timeTableEntries"`
}

type WorkloadAnalysis struct {
	AvgDailyMinutes   float64            `json:"avgDailyMinutes"`
	AvgWeeklyMinutes  float64            `json:"avgWeeklyMinutes"`
	PeakDayMinutes    int32              `json:"peakDayMinutes"`
	PeakDay           string             `json:"peakDay"`
	DistributionByDay []*DayDistribution `json:"distributionByDay"`
	TotalOvertime     int32              `json:"totalOvertime"`
	UsersWithOvertime int32              `json:"usersWithOvertime"`
}

type WorkloadDistribution struct {
	Range      string  `json:"range"`
	UserCount  int32   `json:"userCount"`
	Percentage float64 `json:"percentage"`
}

type Role string

const (
	RoleUser    Role = "USER"
	RoleAdmin   Role = "ADMIN"
	RoleManager Role = "MANAGER"
)

var AllRole = []Role{
	RoleUser,
	RoleAdmin,
	RoleManager,
}

func (e Role) IsValid() bool {
	switch e {
	case RoleUser, RoleAdmin, RoleManager:
		return true
	}
	return false
}

func (e Role) String() string {
	return string(e)
}

func (e *Role) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Role(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Role", str)
	}
	return nil
}

func (e Role) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *Role) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e Role) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
